name: batchhelper
version: 1
cron:
    - description: sendStatuses
    url: cron.php?action=sendStatuses
    schedule: every 1 min
    timezone: Beijing
    
    - description: cleanPictures
    url: cron.php?action=cleanPictures
    schedule: every 1 hour
    timezone: Beijing
    
    - description: collectStatuses
    url: cron.php?action=collectStatuses
    schedule: every 5 mins
    timezone: Beijing